### ISSUE TITLE
Choppy playback

### ISSUE THREAD

**Issue by purplehat7** [PhiladelphiaGameLab/Knobs#1]
Really choppy playback on a physical device, though playback works fine on the simulator. Apparently adjusting the `BUF_SIZE` in `CustomAudioUnit.cpp` from 512 to 1024 has fixed the issue in the past, but doing that causes playback to fail completely.

**Comment by purplehat7** [comment]
@avinashpgs do you have any other suggestions? Was adjusting `BUF_SIZE` the fix you were referring to?

**Comment by avinashpgs** [comment]
I am not really sure in that case. But while you are debugging, try
skipping the Mixer, that way you can make sure if the glitch is arising in
Mixer or not. If it is not part of Mixer, it should be either part of ios
interface(custom AudioUnit ) or the wav file reader mostly.

**Comment by purplehat7** [comment]
Good idea. I'll try that.

**Comment by purplehat7** [comment]
Not entirely sure how I fixed it, but I tweaked a couple things and then readjusted `BUF_SIZE` to 1024 again and now it's working.
